//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StromyatnikovRecipe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Articles
    {
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
