//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StromyatnikovRecipe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipes()
        {
            this.Favorites = new HashSet<Favorites>();
        }
    
        public int ID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Name { get; set; }
        public string Rating { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Time { get; set; }
        public string Calories { get; set; }
        public string Difficulty { get; set; }
        public string Ingredients { get; set; }
        public string Description { get; set; }
    
        public virtual Categories Categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favorites> Favorites { get; set; }
        public virtual Users Users { get; set; }
    }
}
